name: Install Dependencies
description: Sets up Bun, then installs all dependencies

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: lts/krypton

    - name: Install bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      with:
        bun-version-file: .bun-version

    - name: Install dependencies
      shell: bash
      run: bun install

    # TODO: This check can go when this issue is fixed https://github.com/oven-sh/bun/issues/24223
    - name: Check for dirty git repo
      shell: bash
      run: git diff --quiet --ignore-submodules HEAD
